debug: true

server:
  port: 8000
  read_timeout: 5s
  read_header_timeout: 3s
  write_timeout: 10s
  idle_timeout: 120s
  shutdown_timeout: 5s

database:
  url: postgres://postgres:postgres@localhost:5432/glut?sslmode=disable
  min_open_conns: 5
  max_open_conns: 10
  max_conn_lifetime: 10m
  max_conn_idle_time: 5m
  health_check_period: 5m
