version: "3"

services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - glut

volumes:
  pgdata:

networks:
  glut:
    name: glut
